var StickyApp = (function () {
    function formatContent(text, noteId) { var lines = String(text || '').split('\n'), html = '', i, line, match; for (i = 0; i < lines.length; i += 1) { line = lines[i]; match = line.match(/^\[([ xX])\]\s*(.*)$/); if (match) { html += '<label class="note-check"><input type="checkbox" data-note="' + noteId + '" data-line="' + i + '"' + (match[1].toLowerCase() === 'x' ? ' checked' : '') + '><span>' + sanitizeHtml(match[2]) + '</span></label>'; } else { html += sanitizeHtml(line) + (i < lines.length - 1 ? '<br>' : ''); } } return html; }
    function render(query) { var b = document.getElementById('sticky-board'), n = Storage.get('sticky_notes', []), i, x, h = ''; if (!b) { return; } for (i = 0; i < n.length; i += 1) { x = n[i]; if (query && (x.title + x.content).toLowerCase().indexOf(query.toLowerCase()) === -1) { continue; } h += '<article class="sticky-note ' + x.color + '" data-id="' + x.id + '" style="left:' + x.x + 'px;top:' + x.y + 'px;width:' + x.width + 'px;min-height:' + x.height + 'px;z-index:' + (x.zIndex || 1) + '"><div class="note-pin"></div><div class="note-actions"><button class="edit-note" type="button">編集</button><button class="delete-note" type="button">×</button></div><h3>' + Fsn.esc(x.title) + '</h3><p>' + formatContent(x.content, x.id) + '</p>' + (x.due ? '<small class="note-due">期限 ' + x.due + '</small>' : '') + '</article>'; } b.innerHTML = h || '<div class="empty-state">付箋はありません。<br>「新しい付箋」から作成できます。</div>'; var es = b.querySelectorAll('.edit-note'), ds = b.querySelectorAll('.delete-note'), checks = b.querySelectorAll('.note-check input'), notes = b.querySelectorAll('.sticky-note'), actions = b.querySelectorAll('.note-actions'), handle, mini, pin; for (i = 0; i < es.length; i += 1) { es[i].onclick = edit; ds[i].onclick = remove; mini = document.createElement('button'); mini.className = 'minimize-note'; mini.type = 'button'; mini.textContent = '−'; actions[i].appendChild(mini); mini.onclick = toggleMinimize; pin = document.createElement('button'); pin.className = 'pin-note'; pin.type = 'button'; pin.textContent = '◆'; actions[i].appendChild(pin); pin.onclick = togglePin; } for (i = 0; i < checks.length; i += 1) { checks[i].onclick = toggleCheck; } for (i = 0; i < notes.length; i += 1) { notes[i].onmousedown = dragStart; handle = document.createElement('span'); handle.className = 'resize-handle'; handle.style.cssText = 'position:absolute;right:3px;bottom:3px;width:13px;height:13px;cursor:nwse-resize'; notes[i].appendChild(handle); handle.onmousedown = resizeStart; } }
    function get(noteId) { var a = Storage.get('sticky_notes', []), i; for (i = 0; i < a.length; i += 1) { if (a[i].id === noteId) { return a[i]; } } return null; }
    function edit(e) { Fsn.open(get(e.target.parentNode.parentNode.getAttribute('data-id'))); }
    function remove(e) { Fsn.remove(e.target.parentNode.parentNode.getAttribute('data-id')); }
    function toggleCheck(e) { var input = e.target, notes = Storage.get('sticky_notes', []), lines, line, i, j; for (j = 0; j < notes.length; j += 1) { if (notes[j].id === input.getAttribute('data-note')) { lines = notes[j].content.split('\n'); line = parseInt(input.getAttribute('data-line'), 10); for (i = 0; i < lines.length; i += 1) { if (i === line) { lines[i] = '[' + (input.checked ? 'x' : ' ') + ']' + lines[i].substring(3); } } notes[j].content = lines.join('\n'); } } Storage.set('sticky_notes', notes); }
    function dragStart(e) { var target = e.currentTarget, node = e.target, x = node; while (x && x !== target) { if (x.tagName === 'BUTTON' || x.tagName === 'INPUT') { return; } x = x.parentNode; } var board = document.getElementById('sticky-board'), startX = e.clientX, startY = e.clientY, left = parseInt(target.style.left, 10) || 0, top = parseInt(target.style.top, 10) || 0, noteId = target.getAttribute('data-id'); e.preventDefault(); target.style.zIndex = 99; document.onmousemove = function (move) { target.style.left = Math.max(0, left + move.clientX - startX) + 'px'; target.style.top = Math.max(0, top + move.clientY - startY) + 'px'; }; document.onmouseup = function () { var notes = Storage.get('sticky_notes', []), i; for (i = 0; i < notes.length; i += 1) { if (notes[i].id === noteId) { notes[i].x = parseInt(target.style.left, 10); notes[i].y = parseInt(target.style.top, 10); notes[i].zIndex = 99; } } Storage.set('sticky_notes', notes); document.onmousemove = null; document.onmouseup = null; };
    }
    function resizeStart(e) { var handle = e.currentTarget, target = handle.parentNode, startX = e.clientX, startY = e.clientY, startW = target.offsetWidth, startH = target.offsetHeight, noteId = target.getAttribute('data-id'); e.preventDefault(); e.stopPropagation(); document.onmousemove = function (move) { target.style.width = Math.max(180, startW + move.clientX - startX) + 'px'; target.style.minHeight = Math.max(120, startH + move.clientY - startY) + 'px'; }; document.onmouseup = function () { var notes = Storage.get('sticky_notes', []), i; for (i = 0; i < notes.length; i += 1) { if (notes[i].id === noteId) { notes[i].width = target.offsetWidth; notes[i].height = target.offsetHeight; } } Storage.set('sticky_notes', notes); document.onmousemove = null; document.onmouseup = null; };
    }
    function toggleMinimize(e) { var button = e.currentTarget, note = button.parentNode.parentNode, body = note.getElementsByTagName('p')[0], due = note.querySelector('.note-due'), notes = Storage.get('sticky_notes', []), i, minimized; for (i = 0; i < notes.length; i += 1) { if (notes[i].id === note.getAttribute('data-id')) { notes[i].minimized = !notes[i].minimized; minimized = notes[i].minimized; } } Storage.set('sticky_notes', notes); body.style.display = minimized ? 'none' : 'block'; if (due) { due.style.display = minimized ? 'none' : 'block'; } button.textContent = minimized ? '+' : '−'; }
    function togglePin(e) { var note = e.currentTarget.parentNode.parentNode, notes = Storage.get('sticky_notes', []), i; for (i = 0; i < notes.length; i += 1) { if (notes[i].id === note.getAttribute('data-id')) { notes[i].pinned = !notes[i].pinned; note.style.boxShadow = notes[i].pinned ? '0 0 0 3px #6157dc66, 0 12px 22px #64617b30' : ''; e.currentTarget.textContent = notes[i].pinned ? '◇' : '◆'; } } Storage.set('sticky_notes', notes); }
    function toggleArchive(e) { var note = e.currentTarget.parentNode.parentNode, notes = Storage.get('sticky_notes', []), i, archived; for (i = 0; i < notes.length; i += 1) { if (notes[i].id === note.getAttribute('data-id')) { notes[i].archived = !notes[i].archived; archived = notes[i].archived; } } Storage.set('sticky_notes', notes); note.style.opacity = archived ? '0.48' : '1'; e.currentTarget.textContent = archived ? '▣' : '□'; Fsn.toast(archived ? '付箋をアーカイブしました' : 'アーカイブから戻しました'); }
    return { render: render };
}());
